/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 *
 * @author keyro
 */
public class Historial_de_pedidos extends javax.swing.JFrame implements Buttons{

    /**
     * Creates new form Historial_de_pedidos
     */
    public Historial_de_pedidos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Regresar_background = new javax.swing.JPanel();
        Regresar_Lbutton = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ClientesConectados = new javax.swing.JLabel();
        Chef_Background = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Historial de pedidos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Regresar_background.setBackground(new java.awt.Color(255, 221, 153));
        Regresar_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Regresar_Lbutton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Regresar_Lbutton.setText("  Regresar");
        Regresar_Lbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Regresar_Lbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Regresar_LbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Regresar_LbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Regresar_LbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Regresar_LbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Regresar_LbuttonMouseReleased(evt);
            }
        });
        Regresar_background.add(Regresar_Lbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 20));

        getContentPane().add(Regresar_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 60, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tipo", "Nombre", "Celular", "Ubicación"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 520, 210));

        ClientesConectados.setText("Clientes conectados actualmente: ");
        getContentPane().add(ClientesConectados, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 180, 10));

        Chef_Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Chef_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui_Admin_J/Fondo.png"))); // NOI18N
        Chef_Background.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(Chef_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 220, 220));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui_Admin_J/Fondo.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 270));

        setSize(new java.awt.Dimension(770, 307));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Regresar_LbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Regresar_LbuttonMouseClicked
        this.dispose();
        Menu_principal ventantaPrincipal= new Menu_principal();
        ventantaPrincipal.setVisible(true);
    }//GEN-LAST:event_Regresar_LbuttonMouseClicked

    private void Regresar_LbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Regresar_LbuttonMouseEntered
        setColorInicial(Regresar_background);
    }//GEN-LAST:event_Regresar_LbuttonMouseEntered

    private void Regresar_LbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Regresar_LbuttonMouseExited
        setColorSalida(Regresar_background);
    }//GEN-LAST:event_Regresar_LbuttonMouseExited

    private void Regresar_LbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Regresar_LbuttonMousePressed
        presionar(Regresar_background,Regresar_Lbutton);
    }//GEN-LAST:event_Regresar_LbuttonMousePressed

    private void Regresar_LbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Regresar_LbuttonMouseReleased
        soltar(Regresar_background,Regresar_Lbutton);
    }//GEN-LAST:event_Regresar_LbuttonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Historial_de_pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Historial_de_pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Historial_de_pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Historial_de_pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Historial_de_pedidos().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Chef_Background;
    private javax.swing.JLabel ClientesConectados;
    private javax.swing.JLabel Regresar_Lbutton;
    private javax.swing.JPanel Regresar_background;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setColorInicial(JPanel panel) {
        panel.setBackground(new Color(255,196,77,200));
    }

    @Override
    public void setColorSalida(JPanel panel) {
        panel.setBackground(new Color(255,221,153,200));
    }

    @Override
    public void presionar(JPanel panel, JLabel etiqueta) {
        panel.setBackground(new Color(255,221,153,200));
        Border loweredbevel= BorderFactory.createLoweredBevelBorder();
        etiqueta.setBorder(loweredbevel);
    }

    @Override
    public void soltar(JPanel panel, JLabel etiqueta) {
        panel.setBackground(new Color(255,196,77,200));
        Border raisedbevel= BorderFactory.createRaisedBevelBorder();
        etiqueta.setBorder(raisedbevel);
    }
}
