/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui_Admin_J;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;

/**
 *
 * @author keyro
 */
public class Info_platillo extends javax.swing.JFrame implements Buttons{

    /**
     * Creates new form Info_platillo
     */
    public Info_platillo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Imagen_platillo = new javax.swing.JLabel();
        Nombre_label = new javax.swing.JLabel();
        DatosNombre_label = new javax.swing.JLabel();
        Código_label = new javax.swing.JLabel();
        DatosCodigo_label = new javax.swing.JLabel();
        TamPorción_label = new javax.swing.JLabel();
        DatosTamañoPorción_label = new javax.swing.JLabel();
        PiezasPorPorción_label = new javax.swing.JLabel();
        DatosPiezasPorPorción_label = new javax.swing.JLabel();
        CaloríasPorPorción_label = new javax.swing.JLabel();
        DatosCaloríasPorPorción_label = new javax.swing.JLabel();
        CaloríasPorPieza_label = new javax.swing.JLabel();
        DatosCaloríasPorPieza_label = new javax.swing.JLabel();
        Precio_label = new javax.swing.JLabel();
        DatosPrecio_label = new javax.swing.JLabel();
        Descripción_label = new javax.swing.JLabel();
        Regresar_background = new javax.swing.JPanel();
        Regresar_Lbutton = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Información del platillo");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 240, -1));

        Imagen_platillo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Imagen_platillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 200));

        Nombre_label.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        Nombre_label.setText("Aquí se carga el nombre del platillo");
        getContentPane().add(Nombre_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, 20));

        DatosNombre_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DatosNombre_label.setText("Nombre:");
        getContentPane().add(DatosNombre_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        Código_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Código_label.setText("Código:");
        getContentPane().add(Código_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 50, -1));

        DatosCodigo_label.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        DatosCodigo_label.setText("Se debe cargar el código");
        getContentPane().add(DatosCodigo_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, 20));

        TamPorción_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TamPorción_label.setText("Tamaño de porción:");
        getContentPane().add(TamPorción_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        DatosTamañoPorción_label.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        DatosTamañoPorción_label.setText("Inserte tamaño aquí");
        getContentPane().add(DatosTamañoPorción_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, 20));

        PiezasPorPorción_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PiezasPorPorción_label.setText("Piezas por porción: ");
        getContentPane().add(PiezasPorPorción_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        DatosPiezasPorPorción_label.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        DatosPiezasPorPorción_label.setText("Piezas por porción aquí");
        getContentPane().add(DatosPiezasPorPorción_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, 20));

        CaloríasPorPorción_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CaloríasPorPorción_label.setText("Calorías por porción:");
        getContentPane().add(CaloríasPorPorción_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        DatosCaloríasPorPorción_label.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        DatosCaloríasPorPorción_label.setText("Inserte Calorías aquí");
        getContentPane().add(DatosCaloríasPorPorción_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, 20));

        CaloríasPorPieza_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CaloríasPorPieza_label.setText("Calorías por pieza:");
        getContentPane().add(CaloríasPorPieza_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        DatosCaloríasPorPieza_label.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        DatosCaloríasPorPieza_label.setText("Inserte Calorías aquí");
        getContentPane().add(DatosCaloríasPorPieza_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, 20));

        Precio_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Precio_label.setText("Precio:");
        getContentPane().add(Precio_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        DatosPrecio_label.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        DatosPrecio_label.setText("Precio del platillo");
        getContentPane().add(DatosPrecio_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, 20));

        Descripción_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Descripción_label.setText("Descripción del platillo:");
        getContentPane().add(Descripción_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        Regresar_background.setBackground(new java.awt.Color(255, 221, 153));
        Regresar_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Regresar_Lbutton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Regresar_Lbutton.setText("  Regresar");
        Regresar_Lbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Regresar_Lbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Regresar_LbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Regresar_LbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Regresar_LbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Regresar_LbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Regresar_LbuttonMouseReleased(evt);
            }
        });
        Regresar_background.add(Regresar_Lbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 20));

        getContentPane().add(Regresar_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 60, 20));

        Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui_Admin_J/Fondo.png"))); // NOI18N
        Background.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 360));

        setSize(new java.awt.Dimension(498, 399));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    @Override
  public void setColorInicial(javax.swing.JPanel panel){
      panel.setBackground(new Color(255,196,77,200));
  }
    @Override
  public void setColorSalida(javax.swing.JPanel panel){
      panel.setBackground(new Color(255,221,153,200));
  }
    @Override
  public void presionar(javax.swing.JPanel panel, javax.swing.JLabel etiqueta){
        panel.setBackground(new Color(255,221,153,200));
        Border loweredbevel= BorderFactory.createLoweredBevelBorder();
        etiqueta.setBorder(loweredbevel);
  }
    @Override
  public void soltar(javax.swing.JPanel panel, javax.swing.JLabel etiqueta){
        panel.setBackground(new Color(255,196,77,200));
        Border raisedbevel= BorderFactory.createRaisedBevelBorder();
        etiqueta.setBorder(raisedbevel);
  }
    private void Regresar_LbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Regresar_LbuttonMouseClicked
        dispose();
        Menu_principal Menu_p = new Menu_principal();
        Menu_p.setVisible(true);
        
    }//GEN-LAST:event_Regresar_LbuttonMouseClicked

    private void Regresar_LbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Regresar_LbuttonMouseEntered
        setColorInicial(Regresar_background);
    }//GEN-LAST:event_Regresar_LbuttonMouseEntered

    private void Regresar_LbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Regresar_LbuttonMouseExited
        setColorSalida(Regresar_background);
    }//GEN-LAST:event_Regresar_LbuttonMouseExited

    private void Regresar_LbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Regresar_LbuttonMousePressed
        presionar(Regresar_background,Regresar_Lbutton);
    }//GEN-LAST:event_Regresar_LbuttonMousePressed

    private void Regresar_LbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Regresar_LbuttonMouseReleased
        soltar(Regresar_background,Regresar_Lbutton);
    }//GEN-LAST:event_Regresar_LbuttonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Info_platillo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Info_platillo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Info_platillo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Info_platillo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Info_platillo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CaloríasPorPieza_label;
    private javax.swing.JLabel CaloríasPorPorción_label;
    private javax.swing.JLabel Código_label;
    private javax.swing.JLabel DatosCaloríasPorPieza_label;
    private javax.swing.JLabel DatosCaloríasPorPorción_label;
    private javax.swing.JLabel DatosCodigo_label;
    private javax.swing.JLabel DatosNombre_label;
    private javax.swing.JLabel DatosPiezasPorPorción_label;
    private javax.swing.JLabel DatosPrecio_label;
    private javax.swing.JLabel DatosTamañoPorción_label;
    private javax.swing.JLabel Descripción_label;
    private javax.swing.JLabel Imagen_platillo;
    private javax.swing.JLabel Nombre_label;
    private javax.swing.JLabel PiezasPorPorción_label;
    private javax.swing.JLabel Precio_label;
    private javax.swing.JLabel Regresar_Lbutton;
    private javax.swing.JPanel Regresar_background;
    private javax.swing.JLabel TamPorción_label;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
