/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui_Admin_J;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.border.BevelBorder;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;

/**
 *
 * @author keyro
 */
public class Menu_principal extends javax.swing.JFrame implements Buttons {

    /**
     * Creates new form Menu_principal
     */
    public Menu_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClientesConectados = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGeneral = new javax.swing.JTable();
        Barra_background = new javax.swing.JPanel();
        Principal_background = new javax.swing.JPanel();
        Principal_Lbutton = new javax.swing.JLabel();
        Entradas_background = new javax.swing.JPanel();
        Entradas_Lbutton = new javax.swing.JLabel();
        Bebidas_background = new javax.swing.JPanel();
        Bebidas_Lbutton = new javax.swing.JLabel();
        Postres_background = new javax.swing.JPanel();
        Postres_Lbutton = new javax.swing.JLabel();
        Top10_background = new javax.swing.JPanel();
        Top10_Lbutton1 = new javax.swing.JLabel();
        NuncaPedidos_background = new javax.swing.JPanel();
        NuncaPedidos_Lbutton = new javax.swing.JLabel();
        Historial_background = new javax.swing.JPanel();
        Historial_Lbutton = new javax.swing.JLabel();
        Salida_background = new javax.swing.JPanel();
        Salida_Lbutton = new javax.swing.JLabel();
        Eliminar_background = new javax.swing.JPanel();
        Eliminar_Lbutton = new javax.swing.JLabel();
        Editar_background = new javax.swing.JPanel();
        Editar_Lbutton = new javax.swing.JLabel();
        Agregar_background = new javax.swing.JPanel();
        Agregar_Lbutton = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setTitle("Menú principal");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ClientesConectados.setText("Clientes conectados actualmente: ");
        getContentPane().add(ClientesConectados, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        jTableGeneral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Platillo", "Código", "Tam porción", "Piezas/porción", "Kcal/porción", "Kca/pieza", "Precio", "Disponible"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableGeneral.setColumnSelectionAllowed(true);
        jTableGeneral.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableGeneral);
        jTableGeneral.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 670, 310));

        Barra_background.setBackground(new java.awt.Color(255, 221, 153));

        javax.swing.GroupLayout Barra_backgroundLayout = new javax.swing.GroupLayout(Barra_background);
        Barra_background.setLayout(Barra_backgroundLayout);
        Barra_backgroundLayout.setHorizontalGroup(
            Barra_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        Barra_backgroundLayout.setVerticalGroup(
            Barra_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(Barra_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 560, 20));

        Principal_background.setBackground(new java.awt.Color(255, 221, 153));
        Principal_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Principal_Lbutton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Principal_Lbutton.setText("  Principal");
        Principal_Lbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Principal_Lbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Principal_LbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Principal_LbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Principal_LbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Principal_LbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Principal_LbuttonMouseReleased(evt);
            }
        });
        Principal_background.add(Principal_Lbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 20));

        getContentPane().add(Principal_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 20));

        Entradas_background.setBackground(new java.awt.Color(255, 221, 153));
        Entradas_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Entradas_Lbutton.setBackground(new java.awt.Color(255, 221, 153));
        Entradas_Lbutton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Entradas_Lbutton.setText("  Entradas");
        Entradas_Lbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Entradas_Lbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Entradas_LbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Entradas_LbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Entradas_LbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Entradas_LbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Entradas_LbuttonMouseReleased(evt);
            }
        });
        Entradas_background.add(Entradas_Lbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 20));

        getContentPane().add(Entradas_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 20));

        Bebidas_background.setBackground(new java.awt.Color(255, 221, 153));
        Bebidas_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bebidas_Lbutton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Bebidas_Lbutton.setText("   Bebidas");
        Bebidas_Lbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bebidas_Lbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bebidas_LbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bebidas_LbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bebidas_LbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Bebidas_LbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Bebidas_LbuttonMouseReleased(evt);
            }
        });
        Bebidas_background.add(Bebidas_Lbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 20));

        getContentPane().add(Bebidas_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 60, 20));

        Postres_background.setBackground(new java.awt.Color(255, 221, 153));
        Postres_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Postres_Lbutton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Postres_Lbutton.setText("   Postres");
        Postres_Lbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Postres_Lbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Postres_LbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Postres_LbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Postres_LbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Postres_LbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Postres_LbuttonMouseReleased(evt);
            }
        });
        Postres_background.add(Postres_Lbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 20));

        getContentPane().add(Postres_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 60, 20));

        Top10_background.setBackground(new java.awt.Color(255, 221, 153));
        Top10_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Top10_Lbutton1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Top10_Lbutton1.setText("      Top 10");
        Top10_Lbutton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Top10_Lbutton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Top10_Lbutton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Top10_Lbutton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Top10_Lbutton1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Top10_Lbutton1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Top10_Lbutton1MouseReleased(evt);
            }
        });
        Top10_background.add(Top10_Lbutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 20));

        getContentPane().add(Top10_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 80, 20));

        NuncaPedidos_background.setBackground(new java.awt.Color(255, 221, 153));
        NuncaPedidos_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NuncaPedidos_Lbutton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        NuncaPedidos_Lbutton.setText(" Nunca Pedidos");
        NuncaPedidos_Lbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NuncaPedidos_Lbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NuncaPedidos_LbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NuncaPedidos_LbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NuncaPedidos_LbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NuncaPedidos_LbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                NuncaPedidos_LbuttonMouseReleased(evt);
            }
        });
        NuncaPedidos_background.add(NuncaPedidos_Lbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 20));

        getContentPane().add(NuncaPedidos_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 80, 20));

        Historial_background.setBackground(new java.awt.Color(255, 221, 153));
        Historial_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Historial_Lbutton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Historial_Lbutton.setText("     Historial");
        Historial_Lbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Historial_Lbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Historial_LbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Historial_LbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Historial_LbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Historial_LbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Historial_LbuttonMouseReleased(evt);
            }
        });
        Historial_background.add(Historial_Lbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 20));

        getContentPane().add(Historial_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 80, 20));

        Salida_background.setBackground(new java.awt.Color(255, 221, 153));
        Salida_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salida_Lbutton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Salida_Lbutton.setText("     Salir");
        Salida_Lbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Salida_Lbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Salida_LbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Salida_LbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Salida_LbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Salida_LbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Salida_LbuttonMouseReleased(evt);
            }
        });
        Salida_background.add(Salida_Lbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 20));

        getContentPane().add(Salida_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 60, 20));

        Eliminar_background.setBackground(new java.awt.Color(255, 221, 153));
        Eliminar_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Eliminar_Lbutton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Eliminar_Lbutton.setText("  Eliminar");
        Eliminar_Lbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Eliminar_Lbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Eliminar_LbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Eliminar_LbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Eliminar_LbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Eliminar_LbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Eliminar_LbuttonMouseReleased(evt);
            }
        });
        Eliminar_background.add(Eliminar_Lbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 20));

        getContentPane().add(Eliminar_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 60, 20));

        Editar_background.setBackground(new java.awt.Color(255, 221, 153));
        Editar_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Editar_Lbutton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Editar_Lbutton.setText("    Editar");
        Editar_Lbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Editar_Lbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Editar_LbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Editar_LbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Editar_LbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Editar_LbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Editar_LbuttonMouseReleased(evt);
            }
        });
        Editar_background.add(Editar_Lbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 20));

        getContentPane().add(Editar_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 60, 20));

        Agregar_background.setBackground(new java.awt.Color(255, 221, 153));
        Agregar_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Agregar_Lbutton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Agregar_Lbutton.setText("   Agregar");
        Agregar_Lbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Agregar_Lbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Agregar_LbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Agregar_LbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Agregar_LbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Agregar_LbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Agregar_LbuttonMouseReleased(evt);
            }
        });
        Agregar_background.add(Agregar_Lbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 20));

        getContentPane().add(Agregar_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, 60, 20));

        Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui_Admin_J/Fondo.png"))); // NOI18N
        Background.setToolTipText("");
        Background.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 400));

        setSize(new java.awt.Dimension(800, 425));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    @Override
  public void setColorInicial(javax.swing.JPanel panel){
      panel.setBackground(new Color(255,196,77,200));
  }
    @Override
  public void setColorSalida(javax.swing.JPanel panel){
      panel.setBackground(new Color(255,221,153,200));
  }
    @Override
  public void presionar(javax.swing.JPanel panel, javax.swing.JLabel etiqueta){
        panel.setBackground(new Color(255,221,153,200));
        Border loweredbevel= BorderFactory.createLoweredBevelBorder();
        etiqueta.setBorder(loweredbevel);
  }
    @Override
  public void soltar(javax.swing.JPanel panel, javax.swing.JLabel etiqueta){
        panel.setBackground(new Color(255,196,77,200));
        Border raisedbevel= BorderFactory.createRaisedBevelBorder();
        etiqueta.setBorder(raisedbevel);
  }
    private void Eliminar_LbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar_LbuttonMouseClicked
   
        int elección=JOptionPane.showConfirmDialog(null, "Está a punto de eliminar este platillo,\nrecuerde que al ser eliminado\ndesaparecerá, todo registro del mismo.", "¿Eliminar?", JOptionPane.YES_NO_OPTION);
        if(elección==JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "Ha eliminado el platillo", "Confirmación", JOptionPane.PLAIN_MESSAGE);
            //Código para elimiar el platillo del XML
        }
        else if(elección==JOptionPane.NO_OPTION){
            JOptionPane.showMessageDialog(null, "Se ha cancelado la acción.", "Cancelación", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_Eliminar_LbuttonMouseClicked

    private void Eliminar_LbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar_LbuttonMouseEntered
        setColorInicial(Eliminar_background);
    }//GEN-LAST:event_Eliminar_LbuttonMouseEntered

    private void Eliminar_LbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar_LbuttonMouseExited
        setColorSalida(Eliminar_background);
    }//GEN-LAST:event_Eliminar_LbuttonMouseExited

    private void Eliminar_LbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar_LbuttonMousePressed
        presionar(Eliminar_background, Eliminar_Lbutton);
    }//GEN-LAST:event_Eliminar_LbuttonMousePressed

    private void Eliminar_LbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar_LbuttonMouseReleased
        soltar(Eliminar_background,Eliminar_Lbutton);
    }//GEN-LAST:event_Eliminar_LbuttonMouseReleased

    private void Salida_LbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Salida_LbuttonMouseClicked
        super.dispose();
    }//GEN-LAST:event_Salida_LbuttonMouseClicked

    private void Salida_LbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Salida_LbuttonMouseEntered
        setColorInicial(Salida_background);
    }//GEN-LAST:event_Salida_LbuttonMouseEntered

    private void Salida_LbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Salida_LbuttonMouseExited
        setColorSalida(Salida_background);
    }//GEN-LAST:event_Salida_LbuttonMouseExited

    private void Salida_LbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Salida_LbuttonMousePressed
        presionar(Salida_background,Salida_Lbutton);
    }//GEN-LAST:event_Salida_LbuttonMousePressed

    private void Salida_LbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Salida_LbuttonMouseReleased
        soltar(Salida_background,Salida_Lbutton);
    }//GEN-LAST:event_Salida_LbuttonMouseReleased
/*
    Clicked
    */
    private void Entradas_LbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Entradas_LbuttonMouseClicked
        JOptionPane.showConfirmDialog(null, "ahora no funciono.");
    }//GEN-LAST:event_Entradas_LbuttonMouseClicked

    private void Entradas_LbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Entradas_LbuttonMouseEntered
        setColorInicial(Entradas_background);
    }//GEN-LAST:event_Entradas_LbuttonMouseEntered

    private void Entradas_LbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Entradas_LbuttonMouseExited
        setColorSalida(Entradas_background);
    }//GEN-LAST:event_Entradas_LbuttonMouseExited

    private void Entradas_LbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Entradas_LbuttonMousePressed
        presionar(Entradas_background,Entradas_Lbutton);
    }//GEN-LAST:event_Entradas_LbuttonMousePressed

    private void Entradas_LbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Entradas_LbuttonMouseReleased
        soltar(Entradas_background,Entradas_Lbutton);
    }//GEN-LAST:event_Entradas_LbuttonMouseReleased

    private void Historial_LbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Historial_LbuttonMouseEntered
        setColorInicial(Historial_background);
    }//GEN-LAST:event_Historial_LbuttonMouseEntered

    private void Historial_LbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Historial_LbuttonMouseExited
        setColorSalida(Historial_background);
    }//GEN-LAST:event_Historial_LbuttonMouseExited

    private void Historial_LbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Historial_LbuttonMousePressed
        presionar(Historial_background,Historial_Lbutton);
    }//GEN-LAST:event_Historial_LbuttonMousePressed

    private void Historial_LbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Historial_LbuttonMouseReleased
        soltar(Historial_background,Historial_Lbutton);
    }//GEN-LAST:event_Historial_LbuttonMouseReleased

    private void Principal_LbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Principal_LbuttonMouseEntered
        setColorInicial(Principal_background);
    }//GEN-LAST:event_Principal_LbuttonMouseEntered

    private void Principal_LbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Principal_LbuttonMouseExited
        setColorSalida(Principal_background);
    }//GEN-LAST:event_Principal_LbuttonMouseExited

    private void Principal_LbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Principal_LbuttonMousePressed
        presionar(Principal_background,Principal_Lbutton);
    }//GEN-LAST:event_Principal_LbuttonMousePressed

    private void Principal_LbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Principal_LbuttonMouseReleased
        soltar(Principal_background,Principal_Lbutton);
    }//GEN-LAST:event_Principal_LbuttonMouseReleased
/* 
    Clicked
    */
    private void Bebidas_LbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bebidas_LbuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Bebidas_LbuttonMouseClicked
/* 
    Clicked
    */
    private void Principal_LbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Principal_LbuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Principal_LbuttonMouseClicked

    private void Bebidas_LbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bebidas_LbuttonMouseEntered
        setColorInicial(Bebidas_background);
    }//GEN-LAST:event_Bebidas_LbuttonMouseEntered

    private void Bebidas_LbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bebidas_LbuttonMouseExited
        setColorSalida(Bebidas_background);
    }//GEN-LAST:event_Bebidas_LbuttonMouseExited

    private void Bebidas_LbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bebidas_LbuttonMousePressed
        presionar(Bebidas_background,Bebidas_Lbutton);
    }//GEN-LAST:event_Bebidas_LbuttonMousePressed

    private void Bebidas_LbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bebidas_LbuttonMouseReleased
        soltar(Bebidas_background,Bebidas_Lbutton);
    }//GEN-LAST:event_Bebidas_LbuttonMouseReleased
/*
    Clicked
    */
    private void Postres_LbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Postres_LbuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Postres_LbuttonMouseClicked

    private void Postres_LbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Postres_LbuttonMouseEntered
        setColorInicial(Postres_background);
    }//GEN-LAST:event_Postres_LbuttonMouseEntered

    private void Postres_LbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Postres_LbuttonMouseExited
        setColorSalida(Postres_background);
    }//GEN-LAST:event_Postres_LbuttonMouseExited

    private void Postres_LbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Postres_LbuttonMousePressed
        presionar(Postres_background, Postres_Lbutton);
    }//GEN-LAST:event_Postres_LbuttonMousePressed

    private void Postres_LbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Postres_LbuttonMouseReleased
        soltar(Postres_background, Postres_Lbutton);
    }//GEN-LAST:event_Postres_LbuttonMouseReleased
/* Clicked
    
    */
    private void Top10_Lbutton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Top10_Lbutton1MouseClicked
        this.setVisible(false);
        Top_10 ventanaTop10= new Top_10();
        ventanaTop10.setVisible(true);
        
    }//GEN-LAST:event_Top10_Lbutton1MouseClicked

    private void Top10_Lbutton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Top10_Lbutton1MouseEntered
        setColorInicial(Top10_background);
    }//GEN-LAST:event_Top10_Lbutton1MouseEntered

    private void Top10_Lbutton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Top10_Lbutton1MouseExited
        setColorSalida(Top10_background);
    }//GEN-LAST:event_Top10_Lbutton1MouseExited

    private void Top10_Lbutton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Top10_Lbutton1MousePressed
        presionar(Top10_background, Top10_Lbutton1);
    }//GEN-LAST:event_Top10_Lbutton1MousePressed

    private void Top10_Lbutton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Top10_Lbutton1MouseReleased
        soltar(Top10_background, Top10_Lbutton1);
    }//GEN-LAST:event_Top10_Lbutton1MouseReleased
/*Clicked
    
    */
    private void NuncaPedidos_LbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NuncaPedidos_LbuttonMouseClicked
        //Agregar Código de nunca pedidos de Yossi
        //this.setVisible(false);
        //NuncaPedidos ventanta= new NuncaPedidos();
        //ventana.setVisible(true);
    }//GEN-LAST:event_NuncaPedidos_LbuttonMouseClicked

    private void NuncaPedidos_LbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NuncaPedidos_LbuttonMouseEntered
        setColorInicial(NuncaPedidos_background);
    }//GEN-LAST:event_NuncaPedidos_LbuttonMouseEntered

    private void NuncaPedidos_LbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NuncaPedidos_LbuttonMouseExited
        setColorSalida(NuncaPedidos_background);
    }//GEN-LAST:event_NuncaPedidos_LbuttonMouseExited

    private void NuncaPedidos_LbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NuncaPedidos_LbuttonMousePressed
        presionar(NuncaPedidos_background, NuncaPedidos_Lbutton);
    }//GEN-LAST:event_NuncaPedidos_LbuttonMousePressed

    private void NuncaPedidos_LbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NuncaPedidos_LbuttonMouseReleased
        soltar(NuncaPedidos_background, NuncaPedidos_Lbutton);
    }//GEN-LAST:event_NuncaPedidos_LbuttonMouseReleased
/*Clicked
    
    */
    private void Editar_LbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Editar_LbuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Editar_LbuttonMouseClicked

    private void Editar_LbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Editar_LbuttonMouseEntered
        setColorInicial(Editar_background);
    }//GEN-LAST:event_Editar_LbuttonMouseEntered

    private void Editar_LbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Editar_LbuttonMouseExited
        setColorSalida(Editar_background);
    }//GEN-LAST:event_Editar_LbuttonMouseExited

    private void Editar_LbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Editar_LbuttonMousePressed
        presionar(Editar_background,Editar_Lbutton);
    }//GEN-LAST:event_Editar_LbuttonMousePressed

    private void Editar_LbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Editar_LbuttonMouseReleased
        soltar(Editar_background,Editar_Lbutton);
    }//GEN-LAST:event_Editar_LbuttonMouseReleased
/*Clicked
    
    */
    private void Agregar_LbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Agregar_LbuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Agregar_LbuttonMouseClicked

    private void Agregar_LbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Agregar_LbuttonMouseEntered
        setColorInicial(Agregar_background);
    }//GEN-LAST:event_Agregar_LbuttonMouseEntered

    private void Agregar_LbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Agregar_LbuttonMouseExited
        setColorSalida(Agregar_background);
    }//GEN-LAST:event_Agregar_LbuttonMouseExited

    private void Agregar_LbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Agregar_LbuttonMousePressed
        presionar(Agregar_background,Agregar_Lbutton);
    }//GEN-LAST:event_Agregar_LbuttonMousePressed

    private void Agregar_LbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Agregar_LbuttonMouseReleased
       soltar(Agregar_background,Agregar_Lbutton);
    }//GEN-LAST:event_Agregar_LbuttonMouseReleased
/* 
    Clicked
    */
    private void Historial_LbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Historial_LbuttonMouseClicked
        this.setVisible(false);
        Historial_de_pedidos ventantaHistorial=new Historial_de_pedidos();
        ventantaHistorial.setVisible(true);
    }//GEN-LAST:event_Historial_LbuttonMouseClicked
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Agregar_Lbutton;
    private javax.swing.JPanel Agregar_background;
    private javax.swing.JLabel Background;
    private javax.swing.JPanel Barra_background;
    private javax.swing.JLabel Bebidas_Lbutton;
    private javax.swing.JPanel Bebidas_background;
    private javax.swing.JLabel ClientesConectados;
    private javax.swing.JLabel Editar_Lbutton;
    private javax.swing.JPanel Editar_background;
    private javax.swing.JLabel Eliminar_Lbutton;
    private javax.swing.JPanel Eliminar_background;
    private javax.swing.JLabel Entradas_Lbutton;
    private javax.swing.JPanel Entradas_background;
    private javax.swing.JLabel Historial_Lbutton;
    private javax.swing.JPanel Historial_background;
    private javax.swing.JLabel NuncaPedidos_Lbutton;
    private javax.swing.JPanel NuncaPedidos_background;
    private javax.swing.JLabel Postres_Lbutton;
    private javax.swing.JPanel Postres_background;
    private javax.swing.JLabel Principal_Lbutton;
    private javax.swing.JPanel Principal_background;
    private javax.swing.JLabel Salida_Lbutton;
    private javax.swing.JPanel Salida_background;
    private javax.swing.JLabel Top10_Lbutton1;
    private javax.swing.JPanel Top10_background;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableGeneral;
    // End of variables declaration//GEN-END:variables
}
