/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 *
 * @author Jorge
 */
public class Platillos_del_cliente extends javax.swing.JFrame implements Buttons {

    /**
     * Creates new form Platillos_del_cliente
     */
    public Platillos_del_cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre_Label = new javax.swing.JLabel();
        Teléfono_Label = new javax.swing.JLabel();
        Ubicación_Label = new javax.swing.JLabel();
        Regresar_background = new javax.swing.JPanel();
        Regresar_Lbutton = new javax.swing.JLabel();
        jScrollPaneOrdenes = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPaneTextArea = new javax.swing.JScrollPane();
        Ubicación_jTextArea = new javax.swing.JTextArea();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Platillos del cliente");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nombre_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Nombre_Label.setText("Nombre:");
        getContentPane().add(Nombre_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        Teléfono_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Teléfono_Label.setText("Teléfono:");
        getContentPane().add(Teléfono_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, -1));

        Ubicación_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Ubicación_Label.setText("Ubicación:");
        getContentPane().add(Ubicación_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, -1));

        Regresar_background.setBackground(new java.awt.Color(255, 221, 153));
        Regresar_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Regresar_Lbutton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Regresar_Lbutton.setText("  Regresar");
        Regresar_Lbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Regresar_Lbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Regresar_LbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Regresar_LbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Regresar_LbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Regresar_LbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Regresar_LbuttonMouseReleased(evt);
            }
        });
        Regresar_background.add(Regresar_Lbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 20));

        getContentPane().add(Regresar_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 60, 20));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPaneOrdenes.setViewportView(jTextArea1);

        getContentPane().add(jScrollPaneOrdenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 320, 150));

        Ubicación_jTextArea.setColumns(20);
        Ubicación_jTextArea.setRows(5);
        jScrollPaneTextArea.setViewportView(Ubicación_jTextArea);

        getContentPane().add(jScrollPaneTextArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 420, 70));

        Background.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui_Admin_J/Fondo.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 350));

        setSize(new java.awt.Dimension(465, 388));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Regresar_LbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Regresar_LbuttonMouseClicked
        this.dispose();
        Menu_principal ventanaPricipal= new Menu_principal();
        ventanaPricipal.setVisible(true);
    }//GEN-LAST:event_Regresar_LbuttonMouseClicked

    private void Regresar_LbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Regresar_LbuttonMouseEntered
        setColorInicial(Regresar_background);
    }//GEN-LAST:event_Regresar_LbuttonMouseEntered

    private void Regresar_LbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Regresar_LbuttonMouseExited
        setColorSalida(Regresar_background);
    }//GEN-LAST:event_Regresar_LbuttonMouseExited

    private void Regresar_LbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Regresar_LbuttonMousePressed
        presionar(Regresar_background,Regresar_Lbutton);
    }//GEN-LAST:event_Regresar_LbuttonMousePressed

    private void Regresar_LbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Regresar_LbuttonMouseReleased
        soltar(Regresar_background,Regresar_Lbutton);
    }//GEN-LAST:event_Regresar_LbuttonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Platillos_del_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Platillos_del_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Platillos_del_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Platillos_del_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Platillos_del_cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Nombre_Label;
    private javax.swing.JLabel Regresar_Lbutton;
    private javax.swing.JPanel Regresar_background;
    private javax.swing.JLabel Teléfono_Label;
    private javax.swing.JLabel Ubicación_Label;
    private javax.swing.JTextArea Ubicación_jTextArea;
    private javax.swing.JScrollPane jScrollPaneOrdenes;
    private javax.swing.JScrollPane jScrollPaneTextArea;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setColorInicial(JPanel panel) {
        panel.setBackground(new Color(255,196,77,200));
    }

    @Override
    public void setColorSalida(JPanel panel) {
        panel.setBackground(new Color(255,221,153,200));
    }

    @Override
    public void presionar(JPanel panel, JLabel etiqueta) {
        panel.setBackground(new Color(255,221,153,200));
        Border loweredbevel= BorderFactory.createLoweredBevelBorder();
        etiqueta.setBorder(loweredbevel);
    }

    @Override
    public void soltar(JPanel panel, JLabel etiqueta) {
        panel.setBackground(new Color(255,196,77,200));
        Border raisedbevel= BorderFactory.createRaisedBevelBorder();
        etiqueta.setBorder(raisedbevel);
    }
}
