/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import cliente.Utilidades;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 *
 * @author keyro
 */
public class Top_10 extends javax.swing.JFrame implements Buttons{

    /**
     * Creates new form Top_10
     */
    public Top_10() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTop10 = new javax.swing.JTable();
        Eliminar_background = new javax.swing.JPanel();
        Eliminar_Lbutton = new javax.swing.JLabel();
        Regresar_background = new javax.swing.JPanel();
        Regresar_Lbutton = new javax.swing.JLabel();
        Editar_background = new javax.swing.JPanel();
        Editar_Lbutton = new javax.swing.JLabel();
        Agregar_background = new javax.swing.JPanel();
        Agregar_Lbutton = new javax.swing.JLabel();
        ClientesConectados = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Top 10");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableTop10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Posición", "Cant/pedidos", "Nombre", "Código", "Tam/porción", "Pieza/porción", "Kcal/porción", "Kcal/pieza", "Precio", "Disponible"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTop10.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableTop10);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 800, 190));

        Eliminar_background.setBackground(new java.awt.Color(255, 221, 153));
        Eliminar_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Eliminar_Lbutton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Eliminar_Lbutton.setText("  Eliminar");
        Eliminar_Lbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Eliminar_Lbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Eliminar_LbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Eliminar_LbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Eliminar_LbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Eliminar_LbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Eliminar_LbuttonMouseReleased(evt);
            }
        });
        Eliminar_background.add(Eliminar_Lbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 20));

        getContentPane().add(Eliminar_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 60, -1));

        Regresar_background.setBackground(new java.awt.Color(255, 221, 153));
        Regresar_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Regresar_Lbutton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Regresar_Lbutton.setText("  Regresar");
        Regresar_Lbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Regresar_Lbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Regresar_LbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Regresar_LbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Regresar_LbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Regresar_LbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Regresar_LbuttonMouseReleased(evt);
            }
        });
        Regresar_background.add(Regresar_Lbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 20));

        getContentPane().add(Regresar_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 60, 20));

        Editar_background.setBackground(new java.awt.Color(255, 221, 153));
        Editar_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Editar_Lbutton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Editar_Lbutton.setText("    Editar");
        Editar_Lbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Editar_Lbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Editar_LbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Editar_LbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Editar_LbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Editar_LbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Editar_LbuttonMouseReleased(evt);
            }
        });
        Editar_background.add(Editar_Lbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 20));

        getContentPane().add(Editar_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 60, -1));

        Agregar_background.setBackground(new java.awt.Color(255, 221, 153));
        Agregar_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Agregar_Lbutton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Agregar_Lbutton.setText("   Agregar");
        Agregar_Lbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Agregar_Lbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Agregar_LbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Agregar_LbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Agregar_LbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Agregar_LbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Agregar_LbuttonMouseReleased(evt);
            }
        });
        Agregar_background.add(Agregar_Lbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 20));

        getContentPane().add(Agregar_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, 60, 20));

        ClientesConectados.setText("Clientes conectados actualmente: ");
        getContentPane().add(ClientesConectados, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gui_Admin_J/Fondo.png"))); // NOI18N
        Background.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 290));

        setSize(new java.awt.Dimension(854, 289));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Regresar_LbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Regresar_LbuttonMouseClicked
        this.dispose();
        Menu_principal ventanaPrincipal=new Menu_principal();
        ventanaPrincipal.setVisible(true);
    }//GEN-LAST:event_Regresar_LbuttonMouseClicked

    private void Regresar_LbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Regresar_LbuttonMouseEntered
        setColorInicial(Regresar_background);
    }//GEN-LAST:event_Regresar_LbuttonMouseEntered

    private void Regresar_LbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Regresar_LbuttonMouseExited
        setColorSalida(Regresar_background);
    }//GEN-LAST:event_Regresar_LbuttonMouseExited

    private void Regresar_LbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Regresar_LbuttonMousePressed
        presionar(Regresar_background,Regresar_Lbutton);
    }//GEN-LAST:event_Regresar_LbuttonMousePressed

    private void Regresar_LbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Regresar_LbuttonMouseReleased
        soltar(Regresar_background,Regresar_Lbutton);
    }//GEN-LAST:event_Regresar_LbuttonMouseReleased

    private void Eliminar_LbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar_LbuttonMouseClicked

        int elección=JOptionPane.showConfirmDialog(null, "Está a punto de eliminar este platillo,\nrecuerde que al ser eliminado\ndesaparecerá, todo registro del mismo.", "¿Eliminar?", JOptionPane.YES_NO_OPTION);
        if(elección==JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "Ha eliminado el platillo", "Confirmación", JOptionPane.PLAIN_MESSAGE);
            //Código para elimiar el platillo del XML
        }
        else if(elección==JOptionPane.NO_OPTION){
            JOptionPane.showMessageDialog(null, "Se ha cancelado la acción.", "Cancelación", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_Eliminar_LbuttonMouseClicked

    private void Eliminar_LbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar_LbuttonMouseEntered
        setColorInicial(Eliminar_background);
    }//GEN-LAST:event_Eliminar_LbuttonMouseEntered

    private void Eliminar_LbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar_LbuttonMouseExited
        setColorSalida(Eliminar_background);
    }//GEN-LAST:event_Eliminar_LbuttonMouseExited

    private void Eliminar_LbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar_LbuttonMousePressed
        presionar(Eliminar_background, Eliminar_Lbutton);
    }//GEN-LAST:event_Eliminar_LbuttonMousePressed

    private void Eliminar_LbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Eliminar_LbuttonMouseReleased
        soltar(Eliminar_background,Eliminar_Lbutton);
    }//GEN-LAST:event_Eliminar_LbuttonMouseReleased

    private void Editar_LbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Editar_LbuttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Editar_LbuttonMouseClicked

    private void Editar_LbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Editar_LbuttonMouseEntered
        setColorInicial(Editar_background);
    }//GEN-LAST:event_Editar_LbuttonMouseEntered

    private void Editar_LbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Editar_LbuttonMouseExited
        setColorSalida(Editar_background);
    }//GEN-LAST:event_Editar_LbuttonMouseExited

    private void Editar_LbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Editar_LbuttonMousePressed
        presionar(Editar_background,Editar_Lbutton);
    }//GEN-LAST:event_Editar_LbuttonMousePressed

    private void Editar_LbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Editar_LbuttonMouseReleased
        soltar(Editar_background,Editar_Lbutton);
    }//GEN-LAST:event_Editar_LbuttonMouseReleased

    private void Agregar_LbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Agregar_LbuttonMouseClicked
//        Utilidades xml= new Utilidades();
//        String dato=xml.extraerDato("DetalleDescripcion", "coca cola");
//        ClientesConectados.setText(dato);
        
        
    }//GEN-LAST:event_Agregar_LbuttonMouseClicked

    private void Agregar_LbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Agregar_LbuttonMouseEntered
        setColorInicial(Agregar_background);
    }//GEN-LAST:event_Agregar_LbuttonMouseEntered

    private void Agregar_LbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Agregar_LbuttonMouseExited
        setColorSalida(Agregar_background);
    }//GEN-LAST:event_Agregar_LbuttonMouseExited

    private void Agregar_LbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Agregar_LbuttonMousePressed
        presionar(Agregar_background,Agregar_Lbutton);
    }//GEN-LAST:event_Agregar_LbuttonMousePressed

    private void Agregar_LbuttonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Agregar_LbuttonMouseReleased
        soltar(Agregar_background,Agregar_Lbutton);
    }//GEN-LAST:event_Agregar_LbuttonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Top_10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Top_10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Top_10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Top_10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Top_10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Agregar_Lbutton;
    private javax.swing.JPanel Agregar_background;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel ClientesConectados;
    private javax.swing.JLabel Editar_Lbutton;
    private javax.swing.JPanel Editar_background;
    private javax.swing.JLabel Eliminar_Lbutton;
    private javax.swing.JPanel Eliminar_background;
    private javax.swing.JLabel Regresar_Lbutton;
    private javax.swing.JPanel Regresar_background;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTop10;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setColorInicial(JPanel panel) {
        panel.setBackground(new Color(255,196,77,200));
    }

    @Override
    public void setColorSalida(JPanel panel) {
        panel.setBackground(new Color(255,221,153,200));
    }

    @Override
    public void presionar(JPanel panel, JLabel etiqueta) {
        panel.setBackground(new Color(255,221,153,200));
        Border loweredbevel= BorderFactory.createLoweredBevelBorder();
        etiqueta.setBorder(loweredbevel);
    }

    @Override
    public void soltar(JPanel panel, JLabel etiqueta) {
        panel.setBackground(new Color(255,196,77,200));
        Border raisedbevel= BorderFactory.createRaisedBevelBorder();
        etiqueta.setBorder(raisedbevel);
    }
}
